backend:
  name: github
  repo: MailTape/MailTape
  branch: master # Branch to update (master by default)

#local config https://decapcms.org/docs/working-with-a-local-git-repository/#gatsby-focus-wrapper
# local_backend: true
# backend:
#   name: git-gateway
# branch: decapCMSimprov

media_folder: "public/img" # Location where files will be stored in the repo
public_folder: "" # The src attribute for uploaded media

site_url: https://mailta.pe
logo_url: https://mailta.pe/img/logo_MailTape_static.png

slug:
  encoding: "ascii"
  clean_accents: true
  sanitize_replacement: "_"

collections:
  - name: "episodes" # Used in routes, e.g., /admin/collections/blog
    label: "Episodes" # Used in the UI
    label_singular: "Episode"
    description: Welcome! Let's prepare some magic for our dear music lovers 💫
    folder: "src/content/episodes" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    identifier_field: guest_name
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    summary: "{{pubDate | date('DD-MM-YY')}} : Episode {{category}} - {{guest_name | upper}}"
    sortable_fields: ['pubDate','guest_name','category']
    delete: false
    view_filters:
      - label: "Anaïs"
        field: author
        pattern: 'Anaïs G'
      - label: "Anto"
        field: author
        pattern: 'Anto'
      - label: "Jules"
        field: author
        pattern: 'Jules'
      - label: "ImaCrea"
        field: author
        pattern: 'ImaCrea'
      - label: "Inès"
        field: author
        pattern: 'Inès'
      - label: "Ling"
        field: author
        pattern: 'Ling'
      - label: "Sarah"
        field: author
        pattern: 'Sarah'
    view_groups:
      - label: Year
        field: pubDate
        # groups items based on the value matched by the pattern
        pattern: \d{4}
    #preview_path: "{{ category }}/{{guest_name.slug}}"
    fields: # The fields for each document, usually in frontmatter
      - { label: "Published", name: "published", widget: "boolean", default: false, hint: "In order to preview your work, it needs to be published. Then wait a 1-2 minutes and you can go on something like mailta.pe/episodeNumber/my-guest-name/ Ex: mailta.pe/562/tiago-caetano/" }
      - { label: "Publish Date", name: "pubDate", widget: "datetime", date_format: "YYYY-MM-DD",hint: "Episode won't be available on homepage before this date. So don't worry when you publish before in order to preview." }
      - { label: "Episode number", name: "category", widget: "string" }
      - { label: "Guest", name: "guest_name", widget: "string" }
      - { label: "Guest Color", required: false, name: "guest_color", widget: "select", options: ["bliss","dreamy","rough", "trippy", "vibrant"], hint: "This is the color which highlights the episode on homepage"}
      - { label: "Guest Pic", required: false, name: "guestPic", widget: "image", media_library: {media_folder: "/public/img",config: { max_file_size: 10240000 } } }
      - { label: "Curator", name: "author", widget: "select", options: ["Anaïs G","Aloyse","Anto","Jules","ImaCrea","Inès","Ling","Sarah"] }
      - { label: "Illustrator", required: false, name: "illustrator", widget: "select", options: ["Anthony Dujardin","Antoine Gaudin","Babi Brunelio","Camille Célestin","Camille Lemeunier","Jan Henrik","Julie Wojtczak","Lucie Fléty","Marie Alléguède","Meriam Kharbat","Nella Papelita","Noémie Dijon", "Patricia Barros De Miranda","Thibault Daumain"] }
      - { label: "Writer", required: false, name: "writer", widget: "select", options:  ["Anaïs G","Aloyse","Anto","Jules","ImaCrea","Inès","Ling","PS KY","Sarah"]  }
      - { label: "Track 1 - Title", required: false, name: track1_title, widget: "string" }
      - label: "Track1 - Color"
        name: track1_color
        widget: select
        required: false
        options:
          - {label: "Bliss", value: "bliss"}
          - {label: "Dreamy", value: "dreamy"}
          - {label: "Rough", value: "rough"}
          - {label: "Trippy", value: "trippy"}
          - {label: "Vibrant", value: "vibrant"}
      - { label: "Track 1 - Link", required: false, name: track1_link, widget: "string", hint: "https://sounds.mailta.pe/XXX/track1.mp3 where XXX is episode number", default: "https://sounds.mailta.pe/XXX/track1.mp3" }

      - { label: "Track 2 - Title", required: false, name: track2_title, widget: "string" }
      - label: "Track2 - Color"
        name: track2_color
        widget: select
        required: false
        options:
          - {label: "Bliss", value: "bliss"}
          - {label: "Dreamy", value: "dreamy"}
          - {label: "Rough", value: "rough"}
          - {label: "Trippy", value: "trippy"}
          - {label: "Vibrant", value: "vibrant"}
      - { label: "Track 2 - Link", required: false, name: track2_link, widget: "string", hint: "https://sounds.mailta.pe/XXX/track2.mp3 where XXX is episode number", default: "https://sounds.mailta.pe/XXX/track2.mp3" }

      - { label: "Track 3 - Title", required: false, name: track3_title, widget: "string" }
      - label: "Track3 - Color"
        name: track3_color
        widget: select
        required: false
        options:
          - {label: "Bliss", value: "bliss"}
          - {label: "Dreamy", value: "dreamy"}
          - {label: "Rough", value: "rough"}
          - {label: "Trippy", value: "trippy"}
          - {label: "Vibrant", value: "vibrant"}
      - { label: "Track 3 - Link", required: false, name: track3_link, widget: "string", hint: "https://sounds.mailta.pe/XXX/track3.mp3 where XXX is episode number", default: "https://sounds.mailta.pe/XXX/track3.mp3" }

      - { label: "Track 4 - Title", required: false, name: track4_title, widget: "string" }
      - label: "Track4 - Color"
        name: track4_color
        widget: select
        required: false
        options:
          - {label: "Bliss", value: "bliss"}
          - {label: "Dreamy", value: "dreamy"}
          - {label: "Rough", value: "rough"}
          - {label: "Trippy", value: "trippy"}
          - {label: "Vibrant", value: "vibrant"}
      - { label: "Track 4 - Link", required: false, name: track4_link, widget: "string", hint: "https://sounds.mailta.pe/XXX/track4.mp3 where XXX is episode number", default: "https://sounds.mailta.pe/XXX/track4.mp3" }

      - { label: "Track 5 - Title", required: false, name: track5_title, widget: "string" }
      - label: "Track5 - Color"
        name: track5_color
        widget: select
        required: false
        options:
          - {label: "Bliss", value: "bliss"}
          - {label: "Dreamy", value: "dreamy"}
          - {label: "Rough", value: "rough"}
          - {label: "Trippy", value: "trippy"}
          - {label: "Vibrant", value: "vibrant"}
      - { label: "Track 5 - Link", required: false, name: track5_link, widget: "string", hint: "https://sounds.mailta.pe/XXX/track5.mp3 where XXX is episode number", default: "https://sounds.mailta.pe/XXX/track5.mp3" }

      - { label: "Track 6 - Title", required: false, name: track6_title, widget: "string" }
      - label: "Track6 - Color"
        name: track6_color
        widget: select
        required: false
        options:
          - {label: "Bliss", value: "bliss"}
          - {label: "Dreamy", value: "dreamy"}
          - {label: "Rough", value: "rough"}
          - {label: "Trippy", value: "trippy"}
          - {label: "Vibrant", value: "vibrant"}
      - { label: "Track 6 - Link", required: false, name: track6_link, widget: "string", hint: "https://sounds.mailta.pe/XXX/track6.mp3 where XXX is episode number", default: "https://sounds.mailta.pe/XXX/track6.mp3" }

      - { label: "Track 7 - Title", required: false, name: track7_title, widget: "string" }
      - label: "Track7 - Color"
        name: track7_color
        widget: select
        required: false
        options:
          - {label: "Bliss", value: "bliss"}
          - {label: "Dreamy", value: "dreamy"}
          - {label: "Rough", value: "rough"}
          - {label: "Trippy", value: "trippy"}
          - {label: "Vibrant", value: "vibrant"}
      - { label: "Track 7 - Link", required: false, name: track7_link, widget: "string", hint: "https://sounds.mailta.pe/XXX/track7.mp3 where XXX is episode number", default: "https://sounds.mailta.pe/XXX/track7.mp3" }

      
      - { label: 'Episode content', required: false, name: 'body', widget: 'markdown', default: "This morning... \n # Guest's selection \n ## Artist - Track \n Guest: **\"** lorem ipsum **\"** \n ## Artist - Track \n Guest: **\"** lorem ipsum **\"** \n ## Artist - Track \n Guest: **\"** lorem ipsum **\"** \n # Curator's selection \n ## Artist - Track \n Curator: **\"** lorem ipsum **\"** \n ## Artist - Track \n Curator: **\"** lorem ipsum **\"** \n ## Artist - Track \n Curator: **\"** lorem ipsum **\"** \n ## Artist - Track \n Curator: **\"** lorem ipsum **\"** \n\n Thank you... "}
      - { label: "Description", required: false, name: "description", widget: "text" }
      - { label: "Episode URL", required: false, name: "episode_URL", widget: "string", hint: "Warning : be careful with caps and don't forget '/' at end! Convention: https://mailta.pe/129/Valentin-Stip/" }
      - { label: "FB Pic", required: false, name: "image" , widget: "string", hint: "Once fbPic uploaded, write here its FULL PATH. Convention : https://mailta.pe/img/fbPic131.png"}
      - { label: "MusiColor", required: false, name: "musiColor", widget: "image", media_library: {media_folder: "/public/img",config: { max_file_size: 1024000 } } }
      - { label: "Refine image vertical alignment", required: false, name: "alignY", widget: "string", hint: "This let you refine vertical alignement of guestPic. Can be center/top/bottom or any number between 0.0 and 1.0."}
