backend:
  name: github
  repo: MailTape/MailTape
  branch: master # Branch to update (master by default)

#local config https://decapcms.org/docs/working-with-a-local-git-repository/#gatsby-focus-wrapper
# local_backend: true
# backend:
#   name: git-gateway
# branch: decapCMS

media_folder: "public/img" # Location where files will be stored in the repo
public_folder: "" # The src attribute for uploaded media

slug:
  encoding: "ascii"
  clean_accents: true
  sanitize_replacement: "_"

collections:
  - name: "episodes" # Used in routes, e.g., /admin/collections/blog
    label: "Episodes" # Used in the UI
    folder: "src/content/episodes" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    identifier_field: guest_name
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    summary: "Episode {{category}} - {{guest_name}}"
    #preview_path: "{{ category }}/{{guest_name.slug}}"
    fields: # The fields for each document, usually in frontmatter
      - { label: "Published", name: "published", widget: "boolean", default: false }
      - { label: "Publish Date", name: "pubDate", widget: "datetime", date_format: "YYYY-MM-DD" }
      - { label: "Episode number", name: "category", widget: "string" }
      - { label: "Guest", name: "guest_name", widget: "string" }
      - { label: "Guest Color", name: "guest_color", widget: "select", options: ["bliss","dreamy","rough", "trippy", "vibrant"]}
      - { label: "Guest Pic", name: "guestPic", widget: "file", media_library: {media_folder: "/public/img",config: { max_file_size: 10240000 } } }
      - { label: "Curator", name: "author", widget: "select", options: ["Anaïs G","Anto","Jules","ImaCrea","Inès","Ling","Sarah"] }
      - { label: "Illustrator", name: "illustrator", widget: "select", options: ["Anthony Dujardin","Camille Célestin","Camille Lemeunier","Julie Wojtczak","Lucie Fléty","Meriam Kharbat","Nella Papelita","Noémie Dijon", "Patricia Barros De Miranda","Thibault Daumain"] }
      - { label: "Writer", name: "writer", widget: "select", options: ["PS2YK"] }
      
      - { label: "Track 1 - Title", name: track1_title, widget: "string" }
      - label: "Track1 - Color"
        name: track1_color
        widget: select
        options:
          - {label: "Bliss", value: "bliss"}
          - {label: "Dreamy", value: "dreamy"}
          - {label: "Rough", value: "rough"}
          - {label: "Trippy", value: "trippy"}
          - {label: "Vibrant", value: "vibrant"}
      - { label: "Track 1 - Link", name: track1_link, widget: "string", hint: "https://mtsounds.s3.eu-central-1.wasabisys.com/XXX/track1.mp3 where XXX is episode number" }

      - { label: "Track 2 - Title", name: track2_title, widget: "string" }
      - label: "Track2 - Color"
        name: track2_color
        widget: select
        options:
          - {label: "Bliss", value: "bliss"}
          - {label: "Dreamy", value: "dreamy"}
          - {label: "Rough", value: "rough"}
          - {label: "Trippy", value: "trippy"}
          - {label: "Vibrant", value: "vibrant"}
      - { label: "Track 2 - Link", name: track2_link, widget: "string", hint: "https://mtsounds.s3.eu-central-1.wasabisys.com/XXX/track2.mp3 where XXX is episode number" }

      - { label: "Track 3 - Title", name: track3_title, widget: "string" }
      - label: "Track3 - Color"
        name: track3_color
        widget: select
        options:
          - {label: "Bliss", value: "bliss"}
          - {label: "Dreamy", value: "dreamy"}
          - {label: "Rough", value: "rough"}
          - {label: "Trippy", value: "trippy"}
          - {label: "Vibrant", value: "vibrant"}
      - { label: "Track 3 - Link", name: track3_link, widget: "string", hint: "https://mtsounds.s3.eu-central-1.wasabisys.com/XXX/track3.mp3 where XXX is episode number" }

      - { label: "Track 4 - Title", name: track4_title, widget: "string" }
      - label: "Track4 - Color"
        name: track4_color
        widget: select
        options:
          - {label: "Bliss", value: "bliss"}
          - {label: "Dreamy", value: "dreamy"}
          - {label: "Rough", value: "rough"}
          - {label: "Trippy", value: "trippy"}
          - {label: "Vibrant", value: "vibrant"}
      - { label: "Track 4 - Link", name: track4_link, widget: "string", hint: "https://mtsounds.s3.eu-central-1.wasabisys.com/XXX/track4.mp3 where XXX is episode number" }

      - { label: "Track 5 - Title", name: track5_title, widget: "string" }
      - label: "Track5 - Color"
        name: track5_color
        widget: select
        options:
          - {label: "Bliss", value: "bliss"}
          - {label: "Dreamy", value: "dreamy"}
          - {label: "Rough", value: "rough"}
          - {label: "Trippy", value: "trippy"}
          - {label: "Vibrant", value: "vibrant"}
      - { label: "Track 5 - Link", name: track5_link, widget: "string", hint: "https://mtsounds.s3.eu-central-1.wasabisys.com/XXX/track5.mp3 where XXX is episode number" }

      - { label: "Track 6 - Title", name: track6_title, widget: "string" }
      - label: "Track6 - Color"
        name: track6_color
        widget: select
        options:
          - {label: "Bliss", value: "bliss"}
          - {label: "Dreamy", value: "dreamy"}
          - {label: "Rough", value: "rough"}
          - {label: "Trippy", value: "trippy"}
          - {label: "Vibrant", value: "vibrant"}
      - { label: "Track 6 - Link", name: track6_link, widget: "string", hint: "https://mtsounds.s3.eu-central-1.wasabisys.com/XXX/track6.mp3 where XXX is episode number" }

      - { label: "Track 7 - Title", name: track7_title, widget: "string" }
      - label: "Track7 - Color"
        name: track7_color
        widget: select
        options:
          - {label: "Bliss", value: "bliss"}
          - {label: "Dreamy", value: "dreamy"}
          - {label: "Rough", value: "rough"}
          - {label: "Trippy", value: "trippy"}
          - {label: "Vibrant", value: "vibrant"}
      - { label: "Track 7 - Link", name: track7_link, widget: "string", hint: "https://mtsounds.s3.eu-central-1.wasabisys.com/XXX/track7.mp3 where XXX is episode number" }

      
      - { label: 'Episode content', name: 'body', widget: 'markdown' }
      - { label: "Description", name: "description", widget: "text" }
      - { label: "Episode URL", name: "episode_URL", widget: "string", hint: "Warning : be careful with caps and don't forget '/' at end! Convention: https://mailta.pe/129/Valentin-Stip/" }
      - { label: "FB Pic", name: "image", hint: "Once fbPic uploaded, write here its FULL PATH. Convention : https://mailta.pe/img/fbPic131.png"}
      - { label: "MusiColor", name: "musiColor", widget: "file", media_library: {media_folder: "/public/img",config: { max_file_size: 1024000 } } }