name: Build Astro and Publish on Deuxfleurs

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: '22'
          cache: 'npm'

      - run: npm install

      - run: npm run build

      - uses: actions/upload-artifact@v4
        with:
          name: website-build
          path: dist/

  deploy:
    runs-on: node:lts-alpine
    needs: build
    steps:
      - uses: actions/download-artifact@v4
        with:
          name: website-build
          path: build/

      - run: npx --yes dxfl deploy mailtape.deuxfleurs.eu build/ --yes
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.dxfl_id }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.dxfl_secret }}
